name: 'recurly_source_integration_tests'
version: '0.1.0'
profile: 'integration_tests'
config-version: 2

vars:
  recurly_schema: recurly_source_integration_tests
  recurly_source:
    account_balance_history_identifier: "account_balance_history_data"
    account_history_identifier: "account_history_data"
    account_note_history_identifier: "account_note_history_data"
    billing_info_history_identifier: "billing_info_history_data"
    coupon_discount_identifier: "coupon_discount_data"
    coupon_redemption_history_identifier: "coupon_redemption_history_data"
    credit_payment_history_identifier: "credit_payment_history_data"
    invoice_coupon_redemption_history_identifier: "invoice_coupon_redemption_history_data"
    invoice_history_identifier: "invoice_history_data"
    invoice_subscription_history_identifier: "invoice_subscription_history_data"
    line_item_history_identifier: "line_item_history_data"
    plan_currency_history_identifier: "plan_currency_history_data"
    plan_history_identifier: "plan_history_data"
    subscription_add_on_history_identifier: "subscription_add_on_history_data"
    subscription_change_history_identifier: "subscription_change_history_data"
    subscription_history_identifier: "subscription_history_data"
    transaction_identifier: "transaction_data"
    transaction_subscription_identifier: "transaction_subscription_data"

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']

seeds:
  recurly_source_integration_tests:
    account_balance_history_data:
      amount: "{{ 'FLOAT64' if target.type == 'bigquery' else 'float' }}"
    credit_payment_history_data:
      id: string
      account_id: string
      applied_to_invoice_id: string
      original_invoice_id: string
      refund_transaction_id: string
      original_credit_payment_id: string
      uuid: string
      amount: "{{ 'FLOAT64' if target.type == 'bigquery' else 'float' }}"
    coupon_discount_data:
      amount: "{{ 'FLOAT64' if target.type == 'bigquery' else 'float' }}"
    invoice_history_data:
      balance: "{{ 'FLOAT64' if target.type == 'bigquery' else 'float' }}"
    line_item_history_data:
      discount: "{{ 'FLOAT64' if target.type == 'bigquery' else 'float' }}"
    plan_currency_history_data:
      unit_amount: "{{ 'FLOAT64' if target.type == 'bigquery' else 'float' }}"
    subscription_add_on_history_data:
      unit_amount: "{{ 'FLOAT64' if target.type == 'bigquery' else 'float' }}"
    subscription_change_history_data:
      id: string
      plan_id: string
      subscription_id: string
      object: string
      unit_amount: "{{ 'FLOAT64' if target.type == 'bigquery' else 'float' }}"
      quantity: integer
    subscription_history_data:
      unit_amount: "{{ 'FLOAT64' if target.type == 'bigquery' else 'float' }}"
    transaction_data:
      amount: "{{ 'FLOAT64' if target.type == 'bigquery' else 'float' }}"
