name: 'recurly_source_integration_tests'
version: '0.1.0'
profile: 'integration_tests'
config-version: 2

vars:
  recurly_source:
    account_balance_identifier: "account_balance_history_data"
    account_history_identifier: "account_history_data"
    account_note_history_identifier: "account_note_history_data"
    billing_info_history_identifier: "billing_info_history_data"
    coupon_discount_data_identifier: "coupon_discount_data"
    coupon_redemption_history_identifier: "coupon_redemption_history_data"
    credit_payment_history_identifier: "credit_payment_history_data"
    invoice_coupon_redemption_history_identifier: "invoice_coupon_redemption_history_data"
    invoice_history_identifier: "invoice_history_data"
    invoice_subscription_history_identifier: "invoice_subscription_history_data"
    line_item_history_identifier: "line_item_history_data"
    plan_currency_history_identifier: "plan_currency_history_data"
    plan_history_identifier: "plan_history_data"
    subscription_add_on_history_identifier: "subscription_add_on_history_data"
    subscription_change_history_identifier: "subscription_change_history_data"
    subscription_history_identifier: "subscription_history_data"
    transaction: "transaction_data"
    transaction_subscription: "transaction_subscription_data"

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']

seeds:
  recurly_source_integration_tests:
    credit_payment_history_data:
      amount: float
    subscription_change_history_data:
      unit_amount: integer
      quantity: integer
